## Planning:
- Load data
- Check variable and target
- Check correlation between numeric variable

In [2]:
# data processing
import pandas as pd
import numpy as np

# data visualisation
import seaborn as sns
import matplotlib.pyplot as plt

# data modeling 
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import roc_auc_score

from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

# model 
from sklearn.linear_model import LogisticRegression
import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostClassifier, Pool

In [3]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
submit = pd.read_csv("sample_submission.csv")

In [4]:
train['Arrival Delay in Minutes'] = train['Arrival Delay in Minutes'].fillna(train['Departure Delay in Minutes'])

In [5]:
test['Arrival Delay in Minutes'] = test['Arrival Delay in Minutes'].fillna(test['Departure Delay in Minutes'])

In [6]:
# check correlation of numeric variable
# take all column numeric column
numeric_cols = train.drop(columns='id').select_dtypes(include='number').columns.tolist()

In [7]:
non_numeric_cols = train.select_dtypes(exclude='number').columns.tolist()

In [8]:
oof_logit_1 = pd.read_csv("blending\oof_logit_1_5cv.csv")
oof_xgb_2 = pd.read_csv("blending\oof_xgb_2_5cv.csv")
oof_xgb_6 = pd.read_csv("blending\oof_xgb_6_5cv_optuna.csv")
oof_xgb_7 = pd.read_csv("blending\oof_xgb_7_20cv_optuna.csv")
oof_xgb_10 = pd.read_csv("blending\oof_xgb_10_5cv_fe.csv")

In [9]:
sub_logit_1 = pd.read_csv("blending\sub_logit_1.csv")
sub_xgb_2 = pd.read_csv("blending\sub_xgb_2.csv")
sub_xgb_6 = pd.read_csv("blending\sub_xgb_6_5cv_optuna.csv")
sub_xgb_7 = pd.read_csv("blending\sub_xgb_7_20cv_optuna.csv")
sub_xgb_10 = pd.read_csv("blending\sub_xgb_10_5cv_feature_engineering.csv")

In [10]:
sub_logit_1.rename(columns={"satisfaction": oof_logit_1.columns.to_list()[2]}, inplace=True)
sub_xgb_2.rename(columns={"satisfaction": oof_xgb_2.columns.to_list()[2]}, inplace=True)
sub_xgb_6.rename(columns={"satisfaction": oof_xgb_6.columns.to_list()[2]}, inplace=True)
sub_xgb_7.rename(columns={"satisfaction": oof_xgb_7.columns.to_list()[2]}, inplace=True)
sub_xgb_10.rename(columns={"satisfaction": oof_xgb_10.columns.to_list()[2]}, inplace=True)

## Basic Data Process for Modeling

Data preparation - Create Dummy variable

In [11]:
# train_dummy = pd.get_dummies(train, columns=non_numeric_cols, dtype=int)
train_dummy = pd.get_dummies(train, columns=non_numeric_cols,drop_first=True, dtype=int)

In [12]:
test_dummy = pd.get_dummies(test, columns=non_numeric_cols.remove('satisfaction'),drop_first=True, dtype=int)

In [13]:
'''
X = train_dummy.drop(columns=["id","satisfaction_True"])
y = train_dummy["satisfaction_True"]
X_test = test_dummy.drop(columns=["id"])
'''

'\nX = train_dummy.drop(columns=["id","satisfaction_True"])\ny = train_dummy["satisfaction_True"]\nX_test = test_dummy.drop(columns=["id"])\n'

In [14]:
train_data = train_dummy[["id","satisfaction_True"]]

In [15]:
train_data = pd.concat([train_data,oof_logit_1.iloc[:,[2]]],axis=1)

In [16]:
train_data = pd.concat([train_data,oof_xgb_2.iloc[:,[2]],oof_xgb_6.iloc[:,[2]],oof_xgb_7.iloc[:,[2]],oof_xgb_10.iloc[:,[2]]],axis=1)

In [17]:
train_data.head(2)

,id,satisfaction_True,oof_logit_1_5cv,oof_xgb_2_5cv,oof_xgb_6_5cv_optuna,oof_xgb_7_20cv_optuna,oof_xgb_10_5cv_fe
0,0,0,0.089254,0.264970,0.257997,0.232633,0.246623
1,1,1,0.931650,0.957369,0.957024,0.950261,0.973524

In [18]:
test_data = test_dummy[["id"]]

In [19]:
test_data = pd.concat([test_data,sub_logit_1.iloc[:,[1]],sub_xgb_2.iloc[:,[1]],sub_xgb_6.iloc[:,[1]],sub_xgb_7.iloc[:,[1]],sub_xgb_10.iloc[:,[1]]],axis=1)

In [20]:
test_data.head(2)

,id,oof_logit_1_5cv,oof_xgb_2_5cv,oof_xgb_6_5cv_optuna,oof_xgb_7_20cv_optuna,oof_xgb_10_5cv_fe
0,699635,0.089525,0.236491,0.230871,0.229289,0.227331
1,699636,0.582690,0.899090,0.890153,0.891726,0.860838

In [21]:
X = train_data.drop(columns=["id","satisfaction_True"])
y = train_data["satisfaction_True"]
X_test = test_data.drop(columns=["id"])

## Find Optimum Parameter using Optuna for XGBOOST

In [1]:
import optuna

In [22]:
SEED = 42

In [23]:
# define objective using XGBoost
# Step 1: Define the Optuna objective with TimeSeriesSplit on x_train
def objective(trial):
    np.random.seed(42)
    params = {
        # fix parameter
        "objective":"binary:logistic",
        "eval_metric": "auc",
        "n_estimators": 10000,
        "tree_method": "hist",
        "enable_categorical": True,
        "random_state": SEED,
        "colsample_bytree":0.8,
        "subsample":0.8,
        "n_jobs":-1,

        # trial parameter
        "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.2,log=True),
        "max_depth": trial.suggest_int("max_depth", 3, 8),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 1.0,log=True),
        "reg_alpha": trial.suggest_float("alpha", 1e-8, 1.0,log=True),
        "min_child_weight": trial.suggest_int("min_child_weight", 5, 30),

        # early stopping round
        "early_stopping_rounds": 200,
    }
    
    train_idx = int(0.85 * X.shape[0])

    x_tr, x_val = X.iloc[:train_idx], X.iloc[train_idx:]
    y_tr, y_val = y.iloc[:train_idx], y.iloc[train_idx:]

    model = xgb.XGBClassifier(**params)
    model.fit(x_tr, y_tr,
              eval_set=[(x_val, y_val)],
              verbose =False)

    preds = model.predict_proba(x_val)[:,1]
    # rmse = np.sqrt(root_mean_squared_error(y_val, preds))
    score_auc = roc_auc_score(y_val, preds)

    # Save best iteration
    trial.set_user_attr("best_iteration", model.best_iteration)

    return score_auc

In [24]:
# Step 2: Run the Optuna study
study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=150)

[I 2026-10-30 20:16:26,209] A new study created in memory with name: no-name-70530abb-1863-41c0-aba6-b5a0a5edbaf2
[I 2026-10-30 20:16:43,846] Trial 0 finished with value: 0.9605787381187074 and parameters: {'learning_rate': 0.030710573677773714, 'max_depth': 8, 'reg_lambda': 0.007177141927992002, 'alpha': 0.0006155564318973012, 'min_child_weight': 9}. Best is trial 0 with value: 0.9605787381187074.
[I 2026-10-30 20:17:40,573] Trial 1 finished with value: 0.9606529938508499 and parameters: {'learning_rate': 0.015957084694148364, 'max_depth': 3, 'reg_lambda': 0.08499808989182997, 'alpha': 0.0006440507553993703, 'min_child_weight': 23}. Best is trial 1 with value: 0.9606529938508499.
[I 2026-10-30 20:18:06,510] Trial 2 finished with value: 0.9605937658541854 and parameters: {'learning_rate': 0.010636066512540286, 'max_depth': 8, 'reg_lambda': 0.04566054873446119, 'alpha': 4.997040685255803e-07, 'min_child_weight': 9}. Best is trial 1 with value: 0.9606529938508499.
[I 2026-10-30 20:18:59,945] Trial 3 finished with value: 0.9606716602850324 and parameters: {'learning_rate': 0.017322667470546258, 'max_depth': 4, 'reg_lambda': 0.00015777981883364995, 'alpha': 2.85469785779718e-05, 'min_child_weight': 12}. Best is trial 3 with value: 0.9606716602850324.
[I 2026-10-30 20:19:19,961] Trial 4 finished with value: 0.960653050346096 and parameters: {'learning_rate': 0.06252287916406217, 'max_depth': 3, 'reg_lambda': 2.1734877073417355e-06, 'alpha': 8.528933855762793e-06, 'min_child_weight': 16}. Best is trial 3 with value: 0.9606716602850324.
[I 2026-10-30 20:19:34,067] Trial 5 finished with value: 0.9606372228440387 and parameters: {'learning_rate': 0.10508421338691762, 'max_depth': 4, 'reg_lambda': 0.00012997969313168238, 'alpha': 0.0005486767416600901, 'min_child_weight': 6}. Best is trial 3 with value: 0.9606716602850324.
[I 2026-10-30 20:19:59,796] Trial 6 finished with value: 0.9606400047288473 and parameters: {'learning_rate': 0.061721159481070736, 'max_depth': 4, 'reg_lambda': 3.3144597077512234e-08, 'alpha': 0.39001768308022033, 'min_child_weight': 30}. Best is trial 3 with value: 0.9606716602850324.
[I 2026-10-30 20:20:14,291] Trial 7 finished with value: 0.960664964034162 and parameters: {'learning_rate': 0.11265466963346032, 'max_depth': 4, 'reg_lambda': 6.044730070370796e-08, 'alpha': 0.0029775853025212607, 'min_child_weight': 16}. Best is trial 3 with value: 0.9606716602850324.
[I 2026-10-30 20:21:08,108] Trial 8 finished with value: 0.9606785563855358 and parameters: {'learning_rate': 0.014413697528610409, 'max_depth': 5, 'reg_lambda': 1.8841183049085085e-08, 'alpha': 0.1881755597772026, 'min_child_weight': 11}. Best is trial 8 with value: 0.9606785563855358.
[I 2026-10-30 20:21:26,138] Trial 9 finished with value: 0.960683918649307 and parameters: {'learning_rate': 0.07277150634170934, 'max_depth': 4, 'reg_lambda': 0.00014472520367197597, 'alpha': 0.00023641892308789696, 'min_child_weight': 9}. Best is trial 9 with value: 0.960683918649307.
[I 2026-10-30 20:21:39,491] Trial 10 finished with value: 0.9606207630368813 and parameters: {'learning_rate': 0.1788820497328707, 'max_depth': 6, 'reg_lambda': 3.846034326037125e-06, 'alpha': 1.3921787642542257e-08, 'min_child_weight': 21}. Best is trial 9 with value: 0.960683918649307.
[I 2026-10-30 20:21:59,174] Trial 11 finished with value: 0.9606494031823056 and parameters: {'learning_rate': 0.033789062165575805, 'max_depth': 6, 'reg_lambda': 4.007559543846745e-06, 'alpha': 0.6023454950347963, 'min_child_weight': 5}. Best is trial 9 with value: 0.960683918649307.
[I 2026-10-30 20:22:20,654] Trial 12 finished with value: 0.9606567460921175 and parameters: {'learning_rate': 0.05247560847099731, 'max_depth': 5, 'reg_lambda': 0.002517568734552522, 'alpha': 0.028566453312709527, 'min_child_weight': 12}. Best is trial 9 with value: 0.960683918649307.
[I 2026-10-30 20:22:50,350] Trial 13 finished with value: 0.9606637467180272 and parameters: {'learning_rate': 0.025947765155331138, 'max_depth': 5, 'reg_lambda': 0.8121561620563509, 'alpha': 0.037993771352991514, 'min_child_weight': 12}. Best is trial 9 with value: 0.960683918649307.
[I 2026-10-30 20:23:05,659] Trial 14 finished with value: 0.9606248608744756 and parameters: {'learning_rate': 0.10085238144072943, 'max_depth': 7, 'reg_lambda': 4.3925586985276887e-07, 'alpha': 1.5699281843484522e-06, 'min_child_weight': 19}. Best is trial 9 with value: 0.960683918649307.
[I 2026-10-30 20:23:59,225] Trial 15 finished with value: 0.9606927320917313 and parameters: {'learning_rate': 0.011058500546306235, 'max_depth': 5, 'reg_lambda': 5.1633008665101316e-05, 'alpha': 0.008930670859039494, 'min_child_weight': 9}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:24:19,688] Trial 16 finished with value: 0.9606435328293663 and parameters: {'learning_rate': 0.04096768800286834, 'max_depth': 6, 'reg_lambda': 3.3237363913303084e-05, 'alpha': 0.005284323849547155, 'min_child_weight': 8}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:25:07,865] Trial 17 finished with value: 0.9606715870436383 and parameters: {'learning_rate': 0.02257709696964179, 'max_depth': 3, 'reg_lambda': 0.0009180150575181214, 'alpha': 6.27933716096296e-05, 'min_child_weight': 15}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:25:23,080] Trial 18 finished with value: 0.9606163081934969 and parameters: {'learning_rate': 0.07598017866049876, 'max_depth': 7, 'reg_lambda': 2.097263173033571e-05, 'alpha': 0.010672878888974157, 'min_child_weight': 26}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:25:36,578] Trial 19 finished with value: 0.9605985736548406 and parameters: {'learning_rate': 0.18265649986999952, 'max_depth': 5, 'reg_lambda': 0.00019449274146582938, 'alpha': 4.9625403145525745e-06, 'min_child_weight': 7}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:25:54,683] Trial 20 finished with value: 0.9606529892502598 and parameters: {'learning_rate': 0.08184124403970248, 'max_depth': 4, 'reg_lambda': 0.0008209260888793022, 'alpha': 0.0002044867527891013, 'min_child_weight': 14}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:26:52,764] Trial 21 finished with value: 0.960665874766974 and parameters: {'learning_rate': 0.010273519232674172, 'max_depth': 5, 'reg_lambda': 1.230236734827473e-08, 'alpha': 0.11523987396857005, 'min_child_weight': 10}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:27:46,751] Trial 22 finished with value: 0.9606764708460416 and parameters: {'learning_rate': 0.013826900078677823, 'max_depth': 5, 'reg_lambda': 1.9700105116183825e-07, 'alpha': 0.10556072869986353, 'min_child_weight': 11}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:28:16,541] Trial 23 finished with value: 0.9606407272055131 and parameters: {'learning_rate': 0.019233180013244772, 'max_depth': 6, 'reg_lambda': 2.1565386135046715e-05, 'alpha': 0.0021696429796103484, 'min_child_weight': 7}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:29:29,758] Trial 24 finished with value: 0.9606629491597315 and parameters: {'learning_rate': 0.013230710218619773, 'max_depth': 4, 'reg_lambda': 5.667925678378325e-07, 'alpha': 0.023277808719766032, 'min_child_weight': 14}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:29:56,924] Trial 25 finished with value: 0.9606646127331038 and parameters: {'learning_rate': 0.04079750203100613, 'max_depth': 5, 'reg_lambda': 0.01539598160574331, 'alpha': 0.2307138962536583, 'min_child_weight': 18}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:30:09,922] Trial 26 finished with value: 0.9605937932737023 and parameters: {'learning_rate': 0.13943933496654703, 'max_depth': 7, 'reg_lambda': 1.0856366530180216e-05, 'alpha': 0.0018759159590210454, 'min_child_weight': 10}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:31:33,527] Trial 27 finished with value: 0.9606633547477528 and parameters: {'learning_rate': 0.012891535195329292, 'max_depth': 3, 'reg_lambda': 0.00040656631996051145, 'alpha': 0.7807700739627758, 'min_child_weight': 13}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:32:14,078] Trial 28 finished with value: 0.9606775433356005 and parameters: {'learning_rate': 0.022809301101133533, 'max_depth': 4, 'reg_lambda': 0.9328312256143881, 'alpha': 0.00017551843565459424, 'min_child_weight': 5}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:32:41,340] Trial 29 finished with value: 0.9606630825768437 and parameters: {'learning_rate': 0.03291208526057723, 'max_depth': 5, 'reg_lambda': 0.005804440770049373, 'alpha': 0.0006958030669493256, 'min_child_weight': 9}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:33:04,646] Trial 30 finished with value: 0.9606401291288029 and parameters: {'learning_rate': 0.027029361823292443, 'max_depth': 6, 'reg_lambda': 1.4956252634438723e-06, 'alpha': 0.010368772579462627, 'min_child_weight': 8}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:33:54,192] Trial 31 finished with value: 0.9606691503871094 and parameters: {'learning_rate': 0.021323351884885232, 'max_depth': 4, 'reg_lambda': 0.21609746977619437, 'alpha': 0.00011381601850436736, 'min_child_weight': 5}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:34:51,458] Trial 32 finished with value: 0.9606844983236569 and parameters: {'learning_rate': 0.01593786272430016, 'max_depth': 4, 'reg_lambda': 0.5353437048204868, 'alpha': 1.782613641897968e-05, 'min_child_weight': 5}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:36:11,237] Trial 33 finished with value: 0.9606609677775966 and parameters: {'learning_rate': 0.015905562852168265, 'max_depth': 3, 'reg_lambda': 0.045483962080542326, 'alpha': 2.0641878632329703e-07, 'min_child_weight': 7}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:37:14,799] Trial 34 finished with value: 0.9606794154077152 and parameters: {'learning_rate': 0.011235671830330545, 'max_depth': 5, 'reg_lambda': 0.2474437327151973, 'alpha': 2.073643299608434e-05, 'min_child_weight': 10}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:38:43,545] Trial 35 finished with value: 0.9606690258031302 and parameters: {'learning_rate': 0.01185890757787531, 'max_depth': 4, 'reg_lambda': 0.2692196470308866, 'alpha': 2.0076657388409566e-05, 'min_child_weight': 9}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:40:54,360] Trial 36 finished with value: 0.9606771911144242 and parameters: {'learning_rate': 0.010507369840094549, 'max_depth': 3, 'reg_lambda': 0.02166845943271995, 'alpha': 6.6933872190617526e-06, 'min_child_weight': 7}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:41:53,903] Trial 37 finished with value: 0.9606646257987794 and parameters: {'learning_rate': 0.018236362887942826, 'max_depth': 4, 'reg_lambda': 0.12096702182062945, 'alpha': 1.3010913452541573e-06, 'min_child_weight': 10}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:42:39,137] Trial 38 finished with value: 0.9606576073225801 and parameters: {'learning_rate': 0.015535428801565835, 'max_depth': 5, 'reg_lambda': 0.0034454753575511427, 'alpha': 2.0663070376106047e-05, 'min_child_weight': 6}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:44:02,851] Trial 39 finished with value: 0.960658385374374 and parameters: {'learning_rate': 0.011671661673505373, 'max_depth': 4, 'reg_lambda': 7.56051197330762e-05, 'alpha': 0.0005474768852430488, 'min_child_weight': 24}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:44:21,909] Trial 40 finished with value: 0.9605848874514292 and parameters: {'learning_rate': 0.05155924033569953, 'max_depth': 8, 'reg_lambda': 0.04296554057894616, 'alpha': 5.17928565921917e-05, 'min_child_weight': 11}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:45:24,430] Trial 41 finished with value: 0.9606627743373084 and parameters: {'learning_rate': 0.014485881003727984, 'max_depth': 5, 'reg_lambda': 1.3244077006297497e-07, 'alpha': 2.5447255378986115e-06, 'min_child_weight': 8}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:46:34,471] Trial 42 finished with value: 0.9606650503412318 and parameters: {'learning_rate': 0.010035004413287385, 'max_depth': 5, 'reg_lambda': 0.36913636738612154, 'alpha': 2.812580063185489e-07, 'min_child_weight': 11}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:47:15,803] Trial 43 finished with value: 0.9606388269777872 and parameters: {'learning_rate': 0.01748767046293292, 'max_depth': 6, 'reg_lambda': 0.0807517721572322, 'alpha': 1.4104567175980665e-05, 'min_child_weight': 13}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:48:42,665] Trial 44 finished with value: 0.9606679604904916 and parameters: {'learning_rate': 0.012066887523130758, 'max_depth': 4, 'reg_lambda': 1.2039066369876892e-08, 'alpha': 0.06638705394827595, 'min_child_weight': 9}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:49:45,991] Trial 45 finished with value: 0.960660400064781 and parameters: {'learning_rate': 0.014900264728140879, 'max_depth': 5, 'reg_lambda': 0.015396883564650904, 'alpha': 0.00036252227543816516, 'min_child_weight': 16}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:50:09,460] Trial 46 finished with value: 0.9606695500863753 and parameters: {'learning_rate': 0.06072791240236778, 'max_depth': 4, 'reg_lambda': 6.858251705500069e-06, 'alpha': 3.697665056094611e-05, 'min_child_weight': 6}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:50:26,493] Trial 47 finished with value: 0.9606038729825397 and parameters: {'learning_rate': 0.08410021784030934, 'max_depth': 6, 'reg_lambda': 3.247761166061418e-08, 'alpha': 0.0011291664579850447, 'min_child_weight': 12}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:51:07,631] Trial 48 finished with value: 0.9606489348422358 and parameters: {'learning_rate': 0.020359011903350696, 'max_depth': 5, 'reg_lambda': 1.3069174153707526e-06, 'alpha': 0.008730288748068738, 'min_child_weight': 30}. Best is trial 15 with value: 0.9606927320917313.
[I 2026-10-30 20:51:58,956] Trial 49 finished with value: 0.960694684766184 and parameters: {'learning_rate': 0.02674700896769134, 'max_depth': 3, 'reg_lambda': 6.07117053588523e-05, 'alpha': 9.517511665071655e-08, 'min_child_weight': 9}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 20:52:50,004] Trial 50 finished with value: 0.9606836514470352 and parameters: {'learning_rate': 0.028329022588527725, 'max_depth': 3, 'reg_lambda': 4.7398512413048884e-05, 'alpha': 5.1630481218384924e-08, 'min_child_weight': 6}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 20:55:30,882] Trial 51 finished with value: 0.9606718481731311 and parameters: {'learning_rate': 0.030932477843854014, 'max_depth': 3, 'reg_lambda': 6.331361982427454e-05, 'alpha': 3.261494939078736e-08, 'min_child_weight': 6}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 20:56:14,384] Trial 52 finished with value: 0.960666481676817 and parameters: {'learning_rate': 0.036362911391257524, 'max_depth': 3, 'reg_lambda': 0.0001878856874223526, 'alpha': 7.632961393770639e-08, 'min_child_weight': 8}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 20:57:08,193] Trial 53 finished with value: 0.9606841470225985 and parameters: {'learning_rate': 0.02511747526886349, 'max_depth': 3, 'reg_lambda': 4.127339544177041e-05, 'alpha': 1.3313862904531066e-08, 'min_child_weight': 5}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 20:58:01,546] Trial 54 finished with value: 0.960686110002373 and parameters: {'learning_rate': 0.02671798539408664, 'max_depth': 3, 'reg_lambda': 4.275631965378714e-05, 'alpha': 1.6097582733719257e-08, 'min_child_weight': 5}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 20:58:56,151] Trial 55 finished with value: 0.9606889586877494 and parameters: {'learning_rate': 0.024626870404646922, 'max_depth': 3, 'reg_lambda': 0.0004009307519211542, 'alpha': 1.428886353198112e-08, 'min_child_weight': 5}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 20:59:53,159] Trial 56 finished with value: 0.9606928793106138 and parameters: {'learning_rate': 0.024554371621106956, 'max_depth': 3, 'reg_lambda': 0.00042072257517235153, 'alpha': 1.0885207879319113e-08, 'min_child_weight': 5}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:00:49,205] Trial 57 finished with value: 0.9606788644410473 and parameters: {'learning_rate': 0.0236453891124414, 'max_depth': 3, 'reg_lambda': 0.0005480555384232759, 'alpha': 2.7863120530473042e-08, 'min_child_weight': 5}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:01:22,870] Trial 58 finished with value: 0.9606493647213726 and parameters: {'learning_rate': 0.037274731193976784, 'max_depth': 3, 'reg_lambda': 0.00040521225390082437, 'alpha': 1.0459399613800413e-07, 'min_child_weight': 7}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:02:11,411] Trial 59 finished with value: 0.9606715476625872 and parameters: {'learning_rate': 0.02912864112108022, 'max_depth': 3, 'reg_lambda': 0.0011841356897714722, 'alpha': 2.0483073056911537e-08, 'min_child_weight': 6}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:03:04,960] Trial 60 finished with value: 0.9606736517884653 and parameters: {'learning_rate': 0.020899804083650615, 'max_depth': 3, 'reg_lambda': 1.5074959469230042e-05, 'alpha': 1.4108555917710565e-07, 'min_child_weight': 28}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:03:56,719] Trial 61 finished with value: 0.9606840404729323 and parameters: {'learning_rate': 0.024478815985423754, 'max_depth': 3, 'reg_lambda': 3.9123223095001475e-05, 'alpha': 1.3902611526309129e-08, 'min_child_weight': 5}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:04:44,666] Trial 62 finished with value: 0.9606880897282954 and parameters: {'learning_rate': 0.025241200391596233, 'max_depth': 3, 'reg_lambda': 0.0001206485507351857, 'alpha': 1.0247464792406414e-08, 'min_child_weight': 5}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:05:58,514] Trial 63 finished with value: 0.9606650205294083 and parameters: {'learning_rate': 0.016832020678688112, 'max_depth': 3, 'reg_lambda': 0.00012049030627856597, 'alpha': 1.0347422604177557e-08, 'min_child_weight': 21}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:06:29,304] Trial 64 finished with value: 0.960651039888232 and parameters: {'learning_rate': 0.04787028048338088, 'max_depth': 3, 'reg_lambda': 0.00024035831917671748, 'alpha': 6.865880746637201e-08, 'min_child_weight': 8}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:07:21,717] Trial 65 finished with value: 0.9606706890084551 and parameters: {'learning_rate': 0.019099729658476165, 'max_depth': 3, 'reg_lambda': 0.002518265252062483, 'alpha': 5.420333182864849e-07, 'min_child_weight': 6}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:07:52,147] Trial 66 finished with value: 0.9606707889332715 and parameters: {'learning_rate': 0.030603132960013067, 'max_depth': 4, 'reg_lambda': 8.47921844630564e-06, 'alpha': 4.3225663542029195e-08, 'min_child_weight': 5}. Best is trial 49 with value: 0.960694684766184.
[I 2026-10-30 21:08:44,476] Trial 67 finished with value: 0.9606910876568138 and parameters: {'learning_rate': 0.026565136022148175, 'max_depth': 3, 'reg_lambda': 3.854251430335323e-06, 'alpha': 2.1961178905127057e-08, 'min_child_weight': 7}. Best is trial 49 with value: 0.960694684766184.

In [25]:
# Step 4: Train final model on full x_train with best parameters
best_params = study.best_params
best_trial = study.best_trial

print("Best Value (AUC):", study.best_value)
print("Best Params:", best_params)
print("Best iteration (trees):", best_trial.user_attrs["best_iteration"])

Best Value (AUC): 0.9607078523910817
Best Params: {'learning_rate': 0.05892906997827939, 'max_depth': 4, 'reg_lambda': 1.1966459664586488e-05, 'alpha': 1.0510871416902545e-08, 'min_child_weight': 9}
Best iteration (trees): 243

In [26]:
final_params = {
    # fix parameter
        "objective":"binary:logistic",
        "eval_metric": "auc",
        "n_estimators": 10000,
        "tree_method": "hist",
        "enable_categorical": True,
        "random_state": SEED,
        "colsample_bytree":0.8,
        "subsample":0.8,
        "n_jobs":-1,
        # early stopping round
        "early_stopping_rounds": 200,

        **best_params
}

## Model using XGboost 5 fold CV

In [27]:
SEED = 42
N_FOLDS = 5
TARGET = 'satisfaction_True'

In [28]:
# Stratified KFold cross validation
skf = StratifiedKFold(n_splits=N_FOLDS, shuffle=True, random_state=SEED)
FOLDS = list(skf.split(X, y))

In [29]:
def run_cv(fit_predict_fn, name):
    oof = np.zeros(len(X))
    test_pred = np.zeros(len(X_test))
    scores = []
    for fold, (tr_idx, va_idx) in enumerate(FOLDS):
        X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
        y_tr, y_va = y[tr_idx], y[va_idx]
        va_pred, te_pred = fit_predict_fn(X_tr, y_tr, X_va, y_va)
        oof[va_idx] = va_pred
        test_pred += te_pred / N_FOLDS
        auc = roc_auc_score(y_va, va_pred)
        scores.append(auc)
        print(f'  fold {fold}: AUC = {auc:.5f}')
    total = roc_auc_score(y, oof)
    print(f'{name} | OOF AUC = {total:.5f} (mean {np.mean(scores):.5f} ± {np.std(scores):.5f})')
    return oof, test_pred, total

In [30]:
def fit_xgb(X_tr, y_tr, X_va, y_va):
    model = xgb.XGBClassifier(**final_params)
    model.fit(X_tr, y_tr, eval_set=[(X_va, y_va)], verbose=False)
    return (model.predict_proba(X_va)[:, 1],
            model.predict_proba(X_test)[:, 1])

In [31]:
oof_xgb, test_xgb, auc_xgb = run_cv(fit_xgb, 'XGBoost')

  fold 0: AUC = 0.96049
  fold 1: AUC = 0.95931
  fold 2: AUC = 0.96107
  fold 3: AUC = 0.96041
  fold 4: AUC = 0.96037
XGBoost | OOF AUC = 0.95966 (mean 0.96033 ± 0.00057)

In [32]:
def save_sub(pred, name):
    sub = submit.copy()
    sub['satisfaction'] = pred
    sub.to_csv(name, index=False)
    print('saving file:', name)

In [36]:
len(test_xgb)

299844

In [33]:
save_sub(test_xgb,'sub_xgb_12_5cv_stacking_optuna.csv')

saving file: sub_xgb_12_5cv_stacking_optuna.csv

In [37]:
oof_xgb_df = train[['id']].copy()
oof_xgb_df.loc[:,'oof_xgb_12_20cv_stacking_optuna'] = oof_xgb
oof_xgb_df.to_csv('oof_xgb_12_20cv_stacking_optuna.csv')

In [82]:
auc_xgb

0.945144978672748